Repository KiCad/kicad-packages3D-source, pull requests merged in 2019-07, with the labels that each got.

#220 Keystone 3034 battery holder source
  Battery.3dshapes/BatteryHolder_Keystone_3034_1x20mm.FCStd
Labels: Enhancement, Pending 3D merge, Pending reviewer

#228 Repush of Oscillator_SMD_Abracon_ASV-4Pin_7.0x5.1mm to get merged cor…
  Oscillator.3dshapes/Oscillator_SMD_Abracon_ASV-4Pin_7.0x5.1mm.FCStd
Labels: Bug, Enhancement

#201 Removed handmade models in favour for script generated 3D models
  Filter.3dshapes/Filter_1109-5_1.1x0.9mm.FCStd
  Filter.3dshapes/Filter_1411-5_1.4x1.1mm.FCStd
Labels: Addition
