Repository KiCad/kicad-packages3D-source, pull requests merged in 2019-01, with the labels that each got.

#200 Fix orientation of TO-92Flat
  Package_TO_SOT_THT.3dshapes/TO-92Flat.FCStd
Labels: Pending review, bug

#139 Added Pulse PA4320
  Inductor_SMD.3dshapes/L_Pulse_PA4320.FCStd
Labels: Pending 3D merge

#161 Adding SATA_Amphenol_10029364-001LF_Horizontal connector
  Connector_SATA_SAS.3dshapes/SATA_Amphenol_10029364-001LF_Horizontal.fcstd
Labels: Pending 3D merge

#154 Added Potentiometer_Bourns_3314J_Vertical
  Potentiometer_SMD.sdshapes/Potentiometer_Bourns_3314J_Vertical.FCStd
Labels: Pending 3D merge

#159 Adding Vishay_PowerPAK_SO-8
  Package_SO.3dshapes/Vishay_PowerPAK_SO-8.fcstd
Labels: Pending review

#162 Sharp_GP2Y0A41SK0F added.
  OptoDevice.3dshapes/Sharp_GP2Y0A41SK0F.FCStd
Labels: Pending review

#164 muRata_OKI_78SR
  Converter_DCDC/OKI-78SR_Horizontal.FCStd
  Converter_DCDC/OKI-78SR_Vertical.FCStd
Labels: Pending review

#167 Added Potentiometer_Bourns_3314G_Vertical
  Potentiometer.3dshapes/Potentiometer_Bourns_3314G_Vertical.FCStd
Labels: Pending 3D merge, Re-push
