Repository KiCad/kicad-packages3D-source, pull requests merged in 2020-03, with the labels that each got.

#204 Add ESP-12E
  RF_Module.3dshapes/ESP-12E.FCStd
Labels: Addition, Pending 3D merge, Pending reviewer

#235 Removed hand made models in favour for script based models
  Crystal.3dshapes/Crystal_C26-LF_D2.1mm_L6.5mm_Vertical.FCStd
  Crystal.3dshapes/Crystal_C38-LF_D3.0mm_L8.0mm_Vertical.FCStd
Labels: Enhancement, Pending 3D merge, Pending reviewer

#231 Removed hand made model in favour for a scripted version
  LED_SMD.3dshapes/LED_RGB_1210.fcstd
Labels: Enhancement, Pending reviewer

#233 Removed hand made model, there is a script based variant
  Crystal.3dshapes/Crystal_AT310_D3.0mm_L10.0mm_Vertical.FCStd
Labels: Enhancement, Pending 3D merge, Pending reviewer
